sudo: false
language: go
go:
- "1.9"
- "1.10"
- "1.11"
- "1.12"

env:
- GO111MODULE=on

install:
- go get github.com/stretchr/testify
- go get github.com/prometheus/client_golang/prometheus
- go get golang.org/x/net/context
- go get golang.org/x/net/trace
- go get github.com/jpillora/backoff

script:
- go test -v ./...
